-- admin in group admin
set @rootComponentId = (SELECT component_id FROM component_spec where external_key = '/');
insert into component_spec (component_name,  component_type, shared, model_info, owner, component_id, creator_user_id, date_created) values ('My Sandbox', 'gov.nasa.arc.mct.core.components.MineTaxonomyComponent', 0, null, 'admin', 'ba0a3566be09452ba4ab3e2dc2bd403d', 'admin', NOW());
set @parentMaxSeq = (SELECT MAX(seq_no) FROM component_relationship where component_id = @rootComponentId);
insert  into component_relationship  (component_id, associated_component_id, seq_no) values (@rootComponentId, 'ba0a3566be09452ba4ab3e2dc2bd403d', @parentMaxSeq + 1);
set @lastObjVersion = (SELECT max(obj_version) FROM  component_spec where component_id=@rootComponentId);
update component_spec set obj_version = (@lastObjVersion + 1) where component_id=@rootComponentId;
insert into component_spec (component_name,  component_type, shared, model_info, owner, component_id, creator_user_id, date_created) values ('admin\'s Drop Box', 'gov.nasa.arc.mct.core.components.TelemetryUserDropBoxComponent', 1, null, '*', '1c36b0f192e44f1e96144881e5a1cc5c', 'admin', NOW());
insert  into component_relationship  (component_id, associated_component_id, seq_no) values ('ba0a3566be09452ba4ab3e2dc2bd403d', '1c36b0f192e44f1e96144881e5a1cc5c', 0);
set @parentID =  (SELECT component_id FROM  component_spec where component_name like 'admin%Drop Boxes');
set @parentMaxSeq = (SELECT MAX(seq_no) FROM component_relationship where component_id = @parentID);
insert into component_relationship (component_id, associated_component_id, seq_no) values  (@parentID, '1c36b0f192e44f1e96144881e5a1cc5c', @parentMaxSeq + 1);
set @allParentID =  (SELECT component_id FROM  component_spec where component_name like 'All admin%Drop Boxes');
set @nextSeq = (SELECT MAX(seq_no) FROM component_relationship where component_id = @allParentID) + 1;
insert into component_relationship (component_id, associated_component_id, seq_no) values  (@allParentID, '1c36b0f192e44f1e96144881e5a1cc5c', IFNULL(@nextSeq, 0) );
-- testUser1 in group TestUsers
set @rootComponentId = (SELECT component_id FROM component_spec where external_key = '/');
insert into component_spec (component_name,  component_type, shared, model_info, owner, component_id, creator_user_id, date_created) values ('My Sandbox', 'gov.nasa.arc.mct.core.components.MineTaxonomyComponent', 0, null, 'testUser1', '0a3c8c90ddb4450797eab10f8ad271dd', 'testUser1', NOW());
set @parentMaxSeq = (SELECT MAX(seq_no) FROM component_relationship where component_id = @rootComponentId);
insert  into component_relationship  (component_id, associated_component_id, seq_no) values (@rootComponentId, '0a3c8c90ddb4450797eab10f8ad271dd', @parentMaxSeq + 1);
set @lastObjVersion = (SELECT max(obj_version) FROM  component_spec where component_id=@rootComponentId);
update component_spec set obj_version = (@lastObjVersion + 1) where component_id=@rootComponentId;
insert into component_spec (component_name,  component_type, shared, model_info, owner, component_id, creator_user_id, date_created) values ('testUser1\'s Drop Box', 'gov.nasa.arc.mct.core.components.TelemetryUserDropBoxComponent', 1, null, '*', 'a43ffba4bbb6477b8b1b4d6b55bafbe1', 'testUser1', NOW());
insert  into component_relationship  (component_id, associated_component_id, seq_no) values ('0a3c8c90ddb4450797eab10f8ad271dd', 'a43ffba4bbb6477b8b1b4d6b55bafbe1', 0);
set @parentID =  (SELECT component_id FROM  component_spec where component_name like 'TestUsers%Drop Boxes');
set @parentMaxSeq = (SELECT MAX(seq_no) FROM component_relationship where component_id = @parentID);
insert into component_relationship (component_id, associated_component_id, seq_no) values  (@parentID, 'a43ffba4bbb6477b8b1b4d6b55bafbe1', @parentMaxSeq + 1);
set @allParentID =  (SELECT component_id FROM  component_spec where component_name like 'All TestUsers%Drop Boxes');
set @nextSeq = (SELECT MAX(seq_no) FROM component_relationship where component_id = @allParentID) + 1;
insert into component_relationship (component_id, associated_component_id, seq_no) values  (@allParentID, 'a43ffba4bbb6477b8b1b4d6b55bafbe1', IFNULL(@nextSeq, 0) );
-- testUser2 in group TestUsers
set @rootComponentId = (SELECT component_id FROM component_spec where external_key = '/');
insert into component_spec (component_name,  component_type, shared, model_info, owner, component_id, creator_user_id, date_created) values ('My Sandbox', 'gov.nasa.arc.mct.core.components.MineTaxonomyComponent', 0, null, 'testUser2', '36763b0b16bf44fe9c0aea0b947aa397', 'testUser2', NOW());
set @parentMaxSeq = (SELECT MAX(seq_no) FROM component_relationship where component_id = @rootComponentId);
insert  into component_relationship  (component_id, associated_component_id, seq_no) values (@rootComponentId, '36763b0b16bf44fe9c0aea0b947aa397', @parentMaxSeq + 1);
set @lastObjVersion = (SELECT max(obj_version) FROM  component_spec where component_id=@rootComponentId);
update component_spec set obj_version = (@lastObjVersion + 1) where component_id=@rootComponentId;
insert into component_spec (component_name,  component_type, shared, model_info, owner, component_id, creator_user_id, date_created) values ('testUser2\'s Drop Box', 'gov.nasa.arc.mct.core.components.TelemetryUserDropBoxComponent', 1, null, '*', 'a36c459c467648c6937793970b65d1d8', 'testUser2', NOW());
insert  into component_relationship  (component_id, associated_component_id, seq_no) values ('36763b0b16bf44fe9c0aea0b947aa397', 'a36c459c467648c6937793970b65d1d8', 0);
set @parentID =  (SELECT component_id FROM  component_spec where component_name like 'TestUsers%Drop Boxes');
set @parentMaxSeq = (SELECT MAX(seq_no) FROM component_relationship where component_id = @parentID);
insert into component_relationship (component_id, associated_component_id, seq_no) values  (@parentID, 'a36c459c467648c6937793970b65d1d8', @parentMaxSeq + 1);
set @allParentID =  (SELECT component_id FROM  component_spec where component_name like 'All TestUsers%Drop Boxes');
set @nextSeq = (SELECT MAX(seq_no) FROM component_relationship where component_id = @allParentID) + 1;
insert into component_relationship (component_id, associated_component_id, seq_no) values  (@allParentID, 'a36c459c467648c6937793970b65d1d8', IFNULL(@nextSeq, 0) );
-- testUser3 in group TestUsers
set @rootComponentId = (SELECT component_id FROM component_spec where external_key = '/');
insert into component_spec (component_name,  component_type, shared, model_info, owner, component_id, creator_user_id, date_created) values ('My Sandbox', 'gov.nasa.arc.mct.core.components.MineTaxonomyComponent', 0, null, 'testUser3', 'c5ea78b505e74b3c9f8ea65460afee8e', 'testUser3', NOW());
set @parentMaxSeq = (SELECT MAX(seq_no) FROM component_relationship where component_id = @rootComponentId);
insert  into component_relationship  (component_id, associated_component_id, seq_no) values (@rootComponentId, 'c5ea78b505e74b3c9f8ea65460afee8e', @parentMaxSeq + 1);
set @lastObjVersion = (SELECT max(obj_version) FROM  component_spec where component_id=@rootComponentId);
update component_spec set obj_version = (@lastObjVersion + 1) where component_id=@rootComponentId;
insert into component_spec (component_name,  component_type, shared, model_info, owner, component_id, creator_user_id, date_created) values ('testUser3\'s Drop Box', 'gov.nasa.arc.mct.core.components.TelemetryUserDropBoxComponent', 1, null, '*', '5b6e814ca1464a4ab2315bda192718e9', 'testUser3', NOW());
insert  into component_relationship  (component_id, associated_component_id, seq_no) values ('c5ea78b505e74b3c9f8ea65460afee8e', '5b6e814ca1464a4ab2315bda192718e9', 0);
set @parentID =  (SELECT component_id FROM  component_spec where component_name like 'TestUsers%Drop Boxes');
set @parentMaxSeq = (SELECT MAX(seq_no) FROM component_relationship where component_id = @parentID);
insert into component_relationship (component_id, associated_component_id, seq_no) values  (@parentID, '5b6e814ca1464a4ab2315bda192718e9', @parentMaxSeq + 1);
set @allParentID =  (SELECT component_id FROM  component_spec where component_name like 'All TestUsers%Drop Boxes');
set @nextSeq = (SELECT MAX(seq_no) FROM component_relationship where component_id = @allParentID) + 1;
insert into component_relationship (component_id, associated_component_id, seq_no) values  (@allParentID, '5b6e814ca1464a4ab2315bda192718e9', IFNULL(@nextSeq, 0) );
-- testUser4 in group TestUsers
set @rootComponentId = (SELECT component_id FROM component_spec where external_key = '/');
insert into component_spec (component_name,  component_type, shared, model_info, owner, component_id, creator_user_id, date_created) values ('My Sandbox', 'gov.nasa.arc.mct.core.components.MineTaxonomyComponent', 0, null, 'testUser4', '2c2051ef49c6458cbe091411e0909779', 'testUser4', NOW());
set @parentMaxSeq = (SELECT MAX(seq_no) FROM component_relationship where component_id = @rootComponentId);
insert  into component_relationship  (component_id, associated_component_id, seq_no) values (@rootComponentId, '2c2051ef49c6458cbe091411e0909779', @parentMaxSeq + 1);
set @lastObjVersion = (SELECT max(obj_version) FROM  component_spec where component_id=@rootComponentId);
update component_spec set obj_version = (@lastObjVersion + 1) where component_id=@rootComponentId;
insert into component_spec (component_name,  component_type, shared, model_info, owner, component_id, creator_user_id, date_created) values ('testUser4\'s Drop Box', 'gov.nasa.arc.mct.core.components.TelemetryUserDropBoxComponent', 1, null, '*', '6bf7c59c35ff49c2bbd995b2146fc549', 'testUser4', NOW());
insert  into component_relationship  (component_id, associated_component_id, seq_no) values ('2c2051ef49c6458cbe091411e0909779', '6bf7c59c35ff49c2bbd995b2146fc549', 0);
set @parentID =  (SELECT component_id FROM  component_spec where component_name like 'TestUsers%Drop Boxes');
set @parentMaxSeq = (SELECT MAX(seq_no) FROM component_relationship where component_id = @parentID);
insert into component_relationship (component_id, associated_component_id, seq_no) values  (@parentID, '6bf7c59c35ff49c2bbd995b2146fc549', @parentMaxSeq + 1);
set @allParentID =  (SELECT component_id FROM  component_spec where component_name like 'All TestUsers%Drop Boxes');
set @nextSeq = (SELECT MAX(seq_no) FROM component_relationship where component_id = @allParentID) + 1;
insert into component_relationship (component_id, associated_component_id, seq_no) values  (@allParentID, '6bf7c59c35ff49c2bbd995b2146fc549', IFNULL(@nextSeq, 0) );
-- testUser5 in group TestUsers
set @rootComponentId = (SELECT component_id FROM component_spec where external_key = '/');
insert into component_spec (component_name,  component_type, shared, model_info, owner, component_id, creator_user_id, date_created) values ('My Sandbox', 'gov.nasa.arc.mct.core.components.MineTaxonomyComponent', 0, null, 'testUser5', 'dcabd1ad76dc4844b03584f9bcd658f2', 'testUser5', NOW());
set @parentMaxSeq = (SELECT MAX(seq_no) FROM component_relationship where component_id = @rootComponentId);
insert  into component_relationship  (component_id, associated_component_id, seq_no) values (@rootComponentId, 'dcabd1ad76dc4844b03584f9bcd658f2', @parentMaxSeq + 1);
set @lastObjVersion = (SELECT max(obj_version) FROM  component_spec where component_id=@rootComponentId);
update component_spec set obj_version = (@lastObjVersion + 1) where component_id=@rootComponentId;
insert into component_spec (component_name,  component_type, shared, model_info, owner, component_id, creator_user_id, date_created) values ('testUser5\'s Drop Box', 'gov.nasa.arc.mct.core.components.TelemetryUserDropBoxComponent', 1, null, '*', '8d867522c01d4043931b0e05b10b28c3', 'testUser5', NOW());
insert  into component_relationship  (component_id, associated_component_id, seq_no) values ('dcabd1ad76dc4844b03584f9bcd658f2', '8d867522c01d4043931b0e05b10b28c3', 0);
set @parentID =  (SELECT component_id FROM  component_spec where component_name like 'TestUsers%Drop Boxes');
set @parentMaxSeq = (SELECT MAX(seq_no) FROM component_relationship where component_id = @parentID);
insert into component_relationship (component_id, associated_component_id, seq_no) values  (@parentID, '8d867522c01d4043931b0e05b10b28c3', @parentMaxSeq + 1);
set @allParentID =  (SELECT component_id FROM  component_spec where component_name like 'All TestUsers%Drop Boxes');
set @nextSeq = (SELECT MAX(seq_no) FROM component_relationship where component_id = @allParentID) + 1;
insert into component_relationship (component_id, associated_component_id, seq_no) values  (@allParentID, '8d867522c01d4043931b0e05b10b28c3', IFNULL(@nextSeq, 0) );
-- testUser6 in group TestUsers
set @rootComponentId = (SELECT component_id FROM component_spec where external_key = '/');
insert into component_spec (component_name,  component_type, shared, model_info, owner, component_id, creator_user_id, date_created) values ('My Sandbox', 'gov.nasa.arc.mct.core.components.MineTaxonomyComponent', 0, null, 'testUser6', '7db418ea13c740c5be3bccd234e7b5d0', 'testUser6', NOW());
set @parentMaxSeq = (SELECT MAX(seq_no) FROM component_relationship where component_id = @rootComponentId);
insert  into component_relationship  (component_id, associated_component_id, seq_no) values (@rootComponentId, '7db418ea13c740c5be3bccd234e7b5d0', @parentMaxSeq + 1);
set @lastObjVersion = (SELECT max(obj_version) FROM  component_spec where component_id=@rootComponentId);
update component_spec set obj_version = (@lastObjVersion + 1) where component_id=@rootComponentId;
insert into component_spec (component_name,  component_type, shared, model_info, owner, component_id, creator_user_id, date_created) values ('testUser6\'s Drop Box', 'gov.nasa.arc.mct.core.components.TelemetryUserDropBoxComponent', 1, null, '*', '8f8e274699a04d8f83ddf736fdcfa5b7', 'testUser6', NOW());
insert  into component_relationship  (component_id, associated_component_id, seq_no) values ('7db418ea13c740c5be3bccd234e7b5d0', '8f8e274699a04d8f83ddf736fdcfa5b7', 0);
set @parentID =  (SELECT component_id FROM  component_spec where component_name like 'TestUsers%Drop Boxes');
set @parentMaxSeq = (SELECT MAX(seq_no) FROM component_relationship where component_id = @parentID);
insert into component_relationship (component_id, associated_component_id, seq_no) values  (@parentID, '8f8e274699a04d8f83ddf736fdcfa5b7', @parentMaxSeq + 1);
set @allParentID =  (SELECT component_id FROM  component_spec where component_name like 'All TestUsers%Drop Boxes');
set @nextSeq = (SELECT MAX(seq_no) FROM component_relationship where component_id = @allParentID) + 1;
insert into component_relationship (component_id, associated_component_id, seq_no) values  (@allParentID, '8f8e274699a04d8f83ddf736fdcfa5b7', IFNULL(@nextSeq, 0) );
